# Generated by Django 2.1 on 2020-01-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='player',
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
